### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by WALIDMIA-RF71** [James404-cyber/PROHACK-FILE#1]
![IMG_20210508_132306_283](https://user-images.githubusercontent.com/67943738/117530722-974fa580-b000-11eb-8c58-420e7667661d.jpg)

**Comment by James404-cyber** [comment]
Creat a file .hst.txt ai name se.than you give the storage permission,

**Comment by Api1100** [comment]
Bro i think you Don't Run this tool properly , so now you creat a file in your sdcard  .hst.txt  like this name.and must be give the storage permission in your termux
