### ISSUE TITLE
Issu

### ISSUE THREAD

**Issue by WALIDMIA-RF71** [James404-cyber/PROHACK-FILE#2]
Sir run hoy na
![Screenshot_20210718-152543](https://user-images.githubusercontent.com/67943738/126062264-192af9e7-b89f-4644-adb5-e537c2fc691b.png)

**Comment by James404-cyber** [comment]
You mustbe build up 64bit. This tools working only Android version 64bit
device .

**Comment by James404-cyber** [comment]
Maybe you mistake some command, Cheek out github readme file. And run all tools.
